"""Kontenrahmen-Kerne (aus dem FZR-Echtbetrieb übernommen).

SKR45: 1:1-Transkription des Original-DATEV-Exports eines Gesundheitswesen-
Mandanten (Pflegegrad×Kostenträger-Erträge, Behandlungspflege SGB V, …).
SKR04: kuratierter Handels-Kern. Tupel: (nummer, bezeichnung, art, auto, satz).
"""
from __future__ import annotations

SKR45_KERN: list[tuple[str, str, str, bool, str | None]] = [

    # --- Geld / Finanzkonten (aktiv) ---
    ("1220", "Kasse", "aktiv", False, None),
    ("1240", "Bank (Postbank)", "aktiv", False, None),
    ("1260", "Bank", "aktiv", False, None),
    ("1261", "Bank 1", "aktiv", False, None),
    ("1262", "Bank 2", "aktiv", False, None),
    ("1630", "Abziehbare Vorsteuer", "aktiv", False, None),
    ("1631", "Abziehbare Vorsteuer 7 %", "aktiv", False, "7.00"),
    ("1636", "Abziehbare Vorsteuer 19 %", "aktiv", False, "19.00"),
    ("1655", "Forderungen aus Umsatzsteuer-Vorauszahlungen", "aktiv", False, None),
    ("1695", "Geldtransit", "aktiv", False, None),
    ("1698", "Transit Zahlungsverkehr Debitoren (Einzug)", "aktiv", False, None),
    ("1699", "Transit Zahlungsverkehr Kreditoren (Abbuchung)", "aktiv", False, None),
    # --- Eigenkapital / Verbindlichkeiten (passiv) ---
    ("2200", "Gezeichnetes Kapital", "passiv", False, None),
    ("3500", "Verbindlichkeiten aus Lohn und Gehalt", "passiv", False, None),
    ("3504", "Verbindlichkeiten Lohn- und Kirchensteuer", "passiv", False, None),
    ("3508", "Verbindlichkeiten im Rahmen der Zusatzversorgung", "passiv", False, None),
    ("3510", "Vorauszahlige Beiträge gegenüber Sozialversicherungsträgern", "passiv", False, None),
    ("3515", "Lohn- und Gehaltsverrechnungen", "passiv", False, None),
    ("3520", "Verbindlichkeiten Steuern und Abgaben", "passiv", False, None),
    ("3530", "Verbindlichkeiten gegenüber Bewohnern", "passiv", False, None),
    ("3540", "Verbindlichkeiten gegenüber Gesellschaftern", "passiv", False, None),
    ("3600", "Umsatzsteuer", "passiv", False, None),
    ("3604", "Umsatzsteuer 19 %", "passiv", False, "19.00"),
    ("3640", "Umsatzsteuervorauszahlungen", "passiv", False, None),
    ("3650", "Umsatzsteuervorauszahlungen 1/11", "passiv", False, None),
    ("3700", "Verwahrgeldkonto", "passiv", False, None),
    ("3800", "Passive Rechnungsabgrenzung", "passiv", False, None),
    # --- Erträge ambulant nach Pflegegrad × Kostenträger (SGB XI) ---
    ("4000", "Erträge ambulant PG 1 Pflegekassen", "ertrag", False, None),
    ("4001", "Erträge ambulant PG 1 Sozialhilfeträger", "ertrag", False, None),
    ("4002", "Erträge ambulant PG 1 Selbstzahler", "ertrag", False, None),
    ("4003", "Erträge ambulant PG 1 Übrige", "ertrag", False, None),
    ("4009", "Erträge ambulant PG 1 Beihilfeträger", "ertrag", False, None),
    ("4010", "Erträge ambulant PG 2 Pflegekassen", "ertrag", False, None),
    ("4011", "Erträge ambulant PG 2 Sozialhilfeträger", "ertrag", False, None),
    ("4012", "Erträge ambulant PG 2 Selbstzahler", "ertrag", False, None),
    ("4013", "Erträge ambulant PG 2 Übrige", "ertrag", False, None),
    ("4019", "Erträge ambulant PG 2 Beihilfeträger", "ertrag", False, None),
    ("4020", "Erträge ambulant PG 3 Pflegekassen", "ertrag", False, None),
    ("4021", "Erträge ambulant PG 3 Sozialhilfeträger", "ertrag", False, None),
    ("4022", "Erträge ambulant PG 3 Selbstzahler", "ertrag", False, None),
    ("4023", "Erträge ambulant PG 3 Übrige", "ertrag", False, None),
    ("4029", "Erträge ambulant PG 3 Beihilfeträger", "ertrag", False, None),
    ("4030", "Erträge ambulant PG 4 Pflegekassen", "ertrag", False, None),
    ("4031", "Erträge ambulant PG 4 Sozialhilfeträger", "ertrag", False, None),
    ("4032", "Erträge ambulant PG 4 Selbstzahler", "ertrag", False, None),
    ("4033", "Erträge ambulant PG 4 Übrige", "ertrag", False, None),
    ("4039", "Erträge ambulant PG 4 Beihilfeträger", "ertrag", False, None),
    ("4040", "Erträge ambulant PG 5 Pflegekassen", "ertrag", False, None),
    ("4041", "Erträge ambulant PG 5 Sozialhilfeträger", "ertrag", False, None),
    ("4042", "Erträge ambulant PG 5 Selbstzahler", "ertrag", False, None),
    ("4043", "Erträge ambulant PG 5 Übrige", "ertrag", False, None),
    ("4049", "Erträge ambulant PG 5 Beihilfeträger", "ertrag", False, None),
    # --- Erträge ambulant: sonstige Leistungen PV / SGB V / SGB XII ---
    ("4050", "Erträge ambulant § 39 SGB XI (Verhinderungspflege)", "ertrag", False, None),
    ("4060", "Erträge ambulant § 40 SGB XI (Pflegehilfsmittel)", "ertrag", False, None),
    ("4062", "Erträge ambulant § 37 (3) SGB XI (Beratungseinsatz)", "ertrag", False, None),
    ("4064", "Erträge ambulant § 45a SGB XI (Entlastungsbetrag)", "ertrag", False, None),
    ("4065", "Erträge ambulant § 45b SGB XI (Entlastungsbetrag)", "ertrag", False, None),
    ("4080", "Erträge ambulant Auslagen/Zuweisung sonstige PV", "ertrag", False, None),
    ("4081", "Erträge ambulant Hausnotruf", "ertrag", False, None),
    ("4085", "Erträge ambulant haushaltsnahe Dienstleistungen (nicht Pflege VG)", "ertrag", False, None),
    ("4086", "Erträge ambulant private Pflegeleistungen", "ertrag", False, None),
    ("4090", "Erträge ambulant Behandlungspflege nach SGB V", "ertrag", False, None),
    ("4091", "Erträge § 37 (1) SGB V häusliche Krankenpflege", "ertrag", False, None),
    ("4092", "Erträge § 37 (2) SGB V häusliche Krankenpflege", "ertrag", False, None),
    ("4093", "Erträge § 38 SGB V Haushaltshilfe", "ertrag", False, None),
    ("4095", "Erträge ambulant SGB XII", "ertrag", False, None),
    ("4099", "Erträge ambulant Sonstige SGB XII", "ertrag", False, None),
    # --- Zuschüsse / Nebenerlöse / Erstattungen ---
    ("4400", "Zuweisungen und Zuschüsse zu Betriebskosten ambulant", "ertrag", False, None),
    ("4800", "Andere Nebenerlöse — Erstattungen Personal", "ertrag", False, None),
    ("4830", "Sonstige Erstattungen", "ertrag", False, None),
    ("4831", "Erstattungen für Telefonkosten", "ertrag", False, None),
    ("4832", "Erstattungen für Inkontinenzmaterial", "ertrag", False, None),
    ("4834", "Erstattungen AAG/Lohnfortzahlung", "ertrag", False, None),
    ("4835", "Erstattungen Bundesfreiwilligendienst", "ertrag", False, None),
    # --- Finanz-/sonstige Erträge (5xxx) ---
    ("5100", "Sonstige Zinsen und ähnliche Erträge", "ertrag", False, None),
    ("5290", "Gewährte Skonti", "ertrag", False, None),
    ("5300", "Erlösschmälerungen", "ertrag", False, None),
    ("5500", "Sonstige betriebliche Erträge (Umsatzerlöse)", "ertrag", False, None),
    ("5502", "Sonstige betriebliche Erträge (vereinnahmt)", "ertrag", False, None),
    ("5520", "Versicherungsentschädigungen und Schadenersatzleistungen", "ertrag", False, None),
    ("5660", "Spenden und ähnliche Zuwendungen", "ertrag", False, None),
    ("5800", "Sonstige betriebliche Erträge", "ertrag", False, None),
    # --- Personalaufwand (6xxx) ---
    ("6000", "Löhne und Gehälter Leitung der Einrichtung", "aufwand", False, None),
    ("6010", "Löhne und Gehälter Pflegedienst", "aufwand", False, None),
    ("6020", "Löhne und Gehälter Betreuungsdienst", "aufwand", False, None),
    ("6030", "Löhne und Gehälter Hauswirtschaftlicher Dienst", "aufwand", False, None),
    ("6040", "Löhne und Gehälter Verwaltungsdienst", "aufwand", False, None),
    ("6050", "Löhne und Gehälter Technischer Dienst", "aufwand", False, None),
    ("6060", "Löhne und Gehälter Sonstige Dienste", "aufwand", False, None),
    ("6070", "Löhne für Minijobber", "aufwand", False, None),
    ("6085", "Tantiemen Arbeitnehmer", "aufwand", False, None),
    ("6086", "Sonderzahlungen/Einmalzahlungen", "aufwand", False, None),
    ("6089", "Tantiemen Gesellschafter-Geschäftsführer", "aufwand", False, None),
    ("6090", "Zuschüsse der Agenturen für Arbeit (Haben)", "aufwand", False, None),
    ("6092", "Sonstige Personalaufwendungen", "aufwand", False, None),
    ("6100", "Gesetzliche Sozialaufwendungen Leitung der Einrichtung", "aufwand", False, None),
    ("6110", "Gesetzliche Sozialaufwendungen Pflegedienst", "aufwand", False, None),
    ("6120", "Gesetzliche Sozialaufwendungen Betreuungsdienst", "aufwand", False, None),
    ("6130", "Gesetzliche Sozialaufwendungen Hauswirtschaftlicher Dienst", "aufwand", False, None),
    ("6140", "Gesetzliche Sozialaufwendungen Verwaltungsdienst", "aufwand", False, None),
    ("6150", "Gesetzliche Sozialaufwendungen Technischer Dienst", "aufwand", False, None),
    ("6160", "Gesetzliche Sozialaufwendungen Sonstige Dienste", "aufwand", False, None),
    ("6170", "Soziale Abgaben für Minijobber", "aufwand", False, None),
    ("6180", "Beiträge zur Berufsgenossenschaft", "aufwand", False, None),
    ("6200", "Altersversorgung Leitung der Einrichtung", "aufwand", False, None),
    ("6210", "Altersversorgung Pflegedienst", "aufwand", False, None),
    ("6400", "Sonstige Personalaufwendungen Leitung der Einrichtung", "aufwand", False, None),
    ("6409", "Fortbildungskosten Leitung der Einrichtung", "aufwand", False, None),
    ("6410", "Sonstige Personalaufwendungen Pflegedienst", "aufwand", False, None),
    ("6419", "Fortbildungskosten Pflegedienst", "aufwand", False, None),
    # --- Sachaufwand: Lebensmittel / Medizin / Betreuung (65xx/66xx) ---
    ("6500", "Lebensmittel", "aufwand", False, None),
    ("6510", "Getränke", "aufwand", False, None),
    ("6600", "Aufwendungen für Zusatzleistungen Pflege/Betreuung", "aufwand", False, None),
    ("6610", "Aufwendungen für Zusatzleistungen Unterkunft und Verpflegung", "aufwand", False, None),
    ("6620", "Medizinischer Bedarf", "aufwand", False, None),
    ("6630", "Medizinischer Pflegebedarf", "aufwand", False, None),
    ("6633", "Schutzimpfungen nach Vorschrift", "aufwand", False, None),
    ("6634", "Fußpflege", "aufwand", False, None),
    ("6635", "Inkontinenzmaterial/Einmalunterlagen", "aufwand", False, None),
    ("6637", "Desinfektionsmittel Pflegebereich", "aufwand", False, None),
    ("6638", "Klein-Instrumentarium Pflegebereich", "aufwand", False, None),
    ("6640", "Therapeutischer Bedarf", "aufwand", False, None),
    ("6650", "Sonstige soziale Betreuung", "aufwand", False, None),
    ("6662", "Pflegedokumentation inkl. EDV-Material und -Software", "aufwand", False, None),
    ("6683", "Schutzkleidung", "aufwand", False, None),
    ("6690", "Sonstiger Betreuungsaufwand", "aufwand", False, None),
    # --- Energie / Wirtschaftsbedarf (67xx/68xx) ---
    ("6700", "Wasser, Energie (Gas, Strom, Wasser)", "aufwand", False, None),
    ("6710", "Wasser", "aufwand", False, None),
    ("6720", "Strom", "aufwand", False, None),
    ("6730", "Heizung, Brennstoffe", "aufwand", False, None),
    ("6750", "Gas", "aufwand", False, None),
    ("6800", "Materialaufwendungen (eigenfinanziert)", "aufwand", False, None),
    ("6804", "Hausverbrauch Material", "aufwand", False, None),
    ("6808", "Hausverbrauch Reinigung", "aufwand", False, None),
    ("6810", "Hausverbrauch Wäsche", "aufwand", False, None),
    ("6812", "Dienstkleidung", "aufwand", False, None),
    ("6819", "Sonstiger Wirtschaftsbedarf", "aufwand", False, None),
    # --- Fremdleistungen (682x) ---
    ("6820", "Fremdleistungen Wirtschaftsbedarf (bezogene Leistungen)", "aufwand", False, None),
    ("6823", "Fremdleistung Wäscherei", "aufwand", False, None),
    ("6824", "Fremdleistung technischer Dienst (ohne Instandhaltung)", "aufwand", False, None),
    ("6825", "Fremdleistung Verwaltung", "aufwand", False, None),
    ("6826", "Fremdleistung Buchführung", "aufwand", False, None),
    ("6828", "Fremdleistung technischer Dienst (mit Instandhaltung)", "aufwand", False, None),
    ("6829", "Fremdleistung Pflege/Soziale Betreuung (Subunternehmer)", "aufwand", False, None),
    ("6832", "Reinigung (zentrale Gebäudereinigung)", "aufwand", False, None),
    ("6835", "Beförderungsdienste (zentrale Dienstleistungen)", "aufwand", False, None),
    # --- Verwaltung (684x–689x) ---
    ("6840", "Sonstiger Verwaltungsbedarf", "aufwand", False, None),
    ("6842", "Büromaterial", "aufwand", False, None),
    ("6844", "Porto", "aufwand", False, None),
    ("6846", "Telefon/Telefax/Mobilfunk/Internet", "aufwand", False, None),
    ("6850", "Zeitschriften, Bücher, digitale Medien (Fachliteratur)", "aufwand", False, None),
    ("6852", "Rundfunk- und Fernsehgebühren", "aufwand", False, None),
    ("6858", "Nebenkosten des Geldverkehrs", "aufwand", False, None),
    ("6860", "Buchführungskosten", "aufwand", False, None),
    ("6862", "EDV- und Organisationskosten", "aufwand", False, None),
    ("6863", "Aufwendungen für Lizenzen und Konzessionen", "aufwand", False, None),
    ("6864", "Rechtskosten", "aufwand", False, None),
    ("6865", "Beratungskosten", "aufwand", False, None),
    ("6866", "Abschluss- und Prüfungskosten", "aufwand", False, None),
    ("6867", "Fortbildungskosten", "aufwand", False, None),
    ("6868", "Personalbeschaffungskosten", "aufwand", False, None),
    ("6870", "Werbekosten", "aufwand", False, None),
    ("6872", "Geschenke abzugsfähig", "aufwand", False, None),
    ("6880", "Bewirtungskosten", "aufwand", False, None),
    ("6890", "Reisekosten Arbeitnehmer", "aufwand", False, None),
    ("6891", "Reisekosten Arbeitnehmer — Fahrtkosten", "aufwand", False, None),
    ("6892", "Reisekosten Arbeitnehmer — Verpflegungsmehraufwand", "aufwand", False, None),
    ("6893", "Reisekosten Arbeitnehmer — Übernachtungsaufwand", "aufwand", False, None),
    ("6894", "Kilometergelderstattung Arbeitnehmer", "aufwand", False, None),
    # --- Fahrzeuge (Pflegedienst-Flotte, 695x–698x) ---
    ("6950", "Fahrzeugkosten", "aufwand", False, None),
    ("6951", "Laufende Fahrzeug-Betriebskosten", "aufwand", False, None),
    ("6952", "Fremdfahrzeugkosten", "aufwand", False, None),
    ("6953", "Sonstige Fahrzeugkosten", "aufwand", False, None),
    ("6954", "Parkgebühren", "aufwand", False, None),
    ("6960", "Fahrzeug-Versicherungen", "aufwand", False, None),
    ("6961", "Kfz-Steuern", "aufwand", False, None),
    ("6970", "Garagenmiete", "aufwand", False, None),
    ("6971", "Mietleasing Kfz", "aufwand", False, None),
    ("6980", "Mietleasing Elektrofahrzeuge", "aufwand", False, None),
    # --- Steuern / Beiträge / Versicherungen (71xx) ---
    ("7100", "Körperschaftsteuer", "aufwand", False, None),
    ("7110", "Gewerbesteuer", "aufwand", False, None),
    ("7130", "Grundsteuer", "aufwand", False, None),
    ("7153", "Umlage Ausgleichsfonds Pflege", "aufwand", False, None),
    ("7154", "Beiträge zu Verbänden und Organisationen", "aufwand", False, None),
    ("7158", "Versicherungen", "aufwand", False, None),
    # --- Zinsen (72xx) ---
    ("7200", "Zinsen und ähnliche Aufwendungen", "aufwand", False, None),
    ("7212", "Zinsen auf Kontokorrentkonten", "aufwand", False, None),
    # --- Abschreibungen (75xx) ---
    ("7510", "Abschreibungen auf Sachanlagen", "aufwand", False, None),
    ("7511", "Abschreibungen auf abnutzbare bewegliche Wirtschaftsgüter", "aufwand", False, None),
    ("7516", "Sofortabschreibung geringwertiger Wirtschaftsgüter", "aufwand", False, None),
    # --- Miete / Leasing / Instandhaltung (76xx/77xx) ---
    ("7600", "Miete (unbewegliche Wirtschaftsgüter)", "aufwand", False, None),
    ("7650", "Miete für Einrichtung und Ausstattung", "aufwand", False, None),
    ("7670", "Leasing Einrichtung und Ausstattung", "aufwand", False, None),
    ("7710", "Instandhaltung Gebäude", "aufwand", False, None),
    ("7714", "Instandhaltung und Reparaturen (u. a. Fahrzeuge)", "aufwand", False, None),
    ("7716", "Wartungskosten für Hard- und Software", "aufwand", False, None),
    ("7720", "Sonstige betriebliche Aufwendungen", "aufwand", False, None),
    # --- Prüfungen / Vorschriften (78xx) ---
    ("7834", "Aufwendungen Qualitätsprüfung", "aufwand", False, None),
    ("7837", "TÜV-Gebühren", "aufwand", False, None),
    ("7838", "Arbeitsmedizinische Untersuchungen nach Vorschrift", "aufwand", False, None),
]

SKR04_KERN: list[tuple[str, str, str, bool, str | None]] = [

    # --- Finanzkonten (aktiv) ---
    ("1200", "Forderungen aus Lieferungen und Leistungen", "aktiv", False, None),  # Debitoren-Sammelkonto
    ("1400", "Abziehbare Vorsteuer", "aktiv", False, None),
    ("1401", "Abziehbare Vorsteuer 7 %", "aktiv", False, "7.00"),
    ("1406", "Abziehbare Vorsteuer 19 %", "aktiv", False, "19.00"),
    ("1600", "Kasse", "aktiv", False, None),
    ("1800", "Bank", "aktiv", False, None),
    # --- Umsatzsteuer / Verbindlichkeiten (passiv) ---
    ("3300", "Verbindlichkeiten aus Lieferungen und Leistungen", "passiv", False, None),  # Kreditoren-Sammelkonto
    ("3800", "Umsatzsteuer", "passiv", False, None),
    ("3801", "Umsatzsteuer 7 %", "passiv", False, "7.00"),
    ("3806", "Umsatzsteuer 19 %", "passiv", False, "19.00"),
    # --- Erlöse (Erträge; Automatikkonten tragen die USt selbst) ---
    ("4200", "Erlöse", "ertrag", False, None),
    ("4300", "Erlöse 0 % USt", "ertrag", False, "0.00"),
    ("4334", "Erlöse 7 % USt", "ertrag", True, "7.00"),
    ("4400", "Erlöse 19 % USt", "ertrag", True, "19.00"),
    ("4830", "Sonstige betriebliche Erträge", "ertrag", False, None),
    # --- Wareneingang / Materialaufwand (Aufwand) ---
    ("5100", "Einkauf Roh-, Hilfs- und Betriebsstoffe", "aufwand", False, None),
    ("5200", "Wareneingang", "aufwand", False, None),
    ("5300", "Wareneingang 7 % Vorsteuer", "aufwand", True, "7.00"),
    ("5400", "Wareneingang 19 % Vorsteuer", "aufwand", True, "19.00"),
    ("5800", "Bezugsnebenkosten", "aufwand", False, None),
    ("5900", "Fremdleistungen", "aufwand", False, None),
    ("5905", "Fremdleistungen 19 % Vorsteuer", "aufwand", False, "19.00"),
    ("5906", "Fremdleistungen 7 % Vorsteuer", "aufwand", False, "7.00"),
    # --- Betriebliche Aufwendungen (Aufwand) ---
    ("6300", "Sonstige betriebliche Aufwendungen", "aufwand", False, None),
    ("6310", "Miete (unbewegliche Wirtschaftsgüter)", "aufwand", False, None),
    ("6325", "Gas, Strom, Wasser", "aufwand", False, None),
    ("6330", "Reinigung", "aufwand", False, None),
    ("6335", "Instandhaltung betrieblicher Räume", "aufwand", False, None),
    ("6400", "Versicherungen", "aufwand", False, None),
    ("6420", "Beiträge", "aufwand", False, None),
    ("6460", "Reparatur/Instandhaltung Anlagen und Maschinen", "aufwand", False, None),
    ("6495", "Wartungskosten Hard- und Software", "aufwand", False, None),
    ("6530", "Laufende Kfz-Betriebskosten", "aufwand", False, None),
    ("6540", "Kfz-Reparaturen", "aufwand", False, None),
    ("6600", "Werbekosten", "aufwand", False, None),
    ("6640", "Bewirtungskosten", "aufwand", False, None),
    ("6650", "Reisekosten Arbeitnehmer", "aufwand", False, None),
    ("6800", "Porto", "aufwand", False, None),
    ("6805", "Telefon", "aufwand", False, None),
    ("6810", "Internetkosten", "aufwand", False, None),
    ("6815", "Bürobedarf", "aufwand", False, None),
    ("6820", "Fachliteratur", "aufwand", False, None),
    ("6821", "Fortbildungskosten", "aufwand", False, None),
    ("6825", "Rechts- und Beratungskosten", "aufwand", False, None),
    ("6827", "Abschluss- und Prüfungskosten", "aufwand", False, None),
    ("6830", "Buchführungskosten", "aufwand", False, None),
    ("6845", "Werkzeuge und Kleingeräte", "aufwand", False, None),
    ("6850", "Sonstiger Betriebsbedarf", "aufwand", False, None),
    ("6855", "Nebenkosten des Geldverkehrs", "aufwand", False, None),
]
